services:
  db:
    image: postgres:15
    container_name: retail_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-retail}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pipeline:
    build: .
    container_name: retail_pipeline
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ~/.cache/kagglehub:/root/.cache/kagglehub
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-retail}
      - POSTGRES_HOST=db

volumes:
  postgres_data: